// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transporte.src.shared.context;

#nullable disable

namespace Transporte_ejerciciodb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413205934_SegundaMigracion")]
    partial class SegundaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("documents_drivers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("documents_status", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("TypeDocumentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<short?>("ExperienceYears")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LicenseCategory")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonStatusId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("person_states", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("type_document", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid?>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VehicleStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("TypeVehicleId");

                    b.HasIndex("VehicleStateId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("vehicles_states", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentState");

                    b.Navigation("Driver");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentState");

                    b.Navigation("TypeDocument");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonStateEntity", "PersonStatus")
                        .WithMany()
                        .HasForeignKey("PersonStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PersonStatus");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonRoleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeVehicleEntity", "TypeVehicle")
                        .WithMany()
                        .HasForeignKey("TypeVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleStateEntity", "VehicleState")
                        .WithMany()
                        .HasForeignKey("VehicleStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("TypeVehicle");

                    b.Navigation("VehicleState");
                });
#pragma warning restore 612, 618
        }
    }
}
