// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Transporte.src.shared.context;

#nullable disable

namespace Transporte_ejerciciodb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413220228_QuintaMigracion")]
    partial class QuintaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AssignmentRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("assignment_role", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NewValues")
                        .HasColumnType("json");

                    b.Property<string>("OldValues")
                        .HasColumnType("json");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CompanyDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("company_documents", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CompanyStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("companies_states", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CompanyVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VehicleId");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DiscardStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("discards_status", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentCustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("documents_customers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("documents_drivers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("documents_status", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("DocumentStateId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStateId");

                    b.HasIndex("TypeDocumentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<short?>("ExperienceYears")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LicenseCategory")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DestinationCityId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("OriginCityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("TypeLoadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TypeLoadId");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("load_images", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<Point>("LocationPoint")
                        .HasColumnType("point");

                    b.Property<string>("PointType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("load_points", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("LeadId");

                    b.ToTable("load_status_history", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonStatusId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("person_states", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DestinationCityId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("OriginCityId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("SuggestedPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("TypeLoadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TypeLoadId");

                    b.HasIndex("TypeVehicleId");

                    b.ToTable("prices");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PriceHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal?>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PriceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReasonChange")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.ReasonDiscardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("reasons_discards", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.ReturnLoadSuggestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("TripId");

                    b.ToTable("return_load_suggestions", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TransportCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("CompanyStateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("LegalRepresentativeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyStateId");

                    b.HasIndex("LegalRepresentativeId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("transport_companies", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TravelAreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<short?>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TripId");

                    b.ToTable("travel_areas", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("AssignmentRoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentRoleId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TripId");

                    b.ToTable("trip_assignments", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("PickupDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("TripStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripStatesHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Point>("LocationPoint")
                        .HasColumnType("point");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("trip_states_history", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("type_document", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeLoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("type_load", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeVehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid?>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VehicleStateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("TypeVehicleId");

                    b.HasIndex("VehicleStateId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("vehicles_states", (string)null);
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuditLogEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthCredentialEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.AuthSessionEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CompanyDocumentEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TransportCompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("DocumentState");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CompanyVehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TransportCompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentCustomerEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("DocumentState");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentDriverEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentState");

                    b.Navigation("Driver");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DocumentVehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentStatusEntity", "DocumentState")
                        .WithMany()
                        .HasForeignKey("DocumentStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentState");

                    b.Navigation("TypeDocument");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.DriverVehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DriverEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeLoadEntity", "TypeLoad")
                        .WithMany()
                        .HasForeignKey("TypeLoadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");

                    b.Navigation("TypeLoad");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadImageEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadPointEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.LoadStatusHistoryEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedBy");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonStateEntity", "PersonStatus")
                        .WithMany()
                        .HasForeignKey("PersonStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PersonStatus");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PersonRoleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PriceEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId");

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId");

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeLoadEntity", "TypeLoad")
                        .WithMany()
                        .HasForeignKey("TypeLoadId");

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeVehicleEntity", "TypeVehicle")
                        .WithMany()
                        .HasForeignKey("TypeVehicleId");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");

                    b.Navigation("TypeLoad");

                    b.Navigation("TypeVehicle");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.PriceHistoryEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PriceEntity", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.ReturnLoadSuggestionEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lead");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TransportCompanyEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CompanyStateEntity", "CompanyState")
                        .WithMany()
                        .HasForeignKey("CompanyStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "LegalRepresentative")
                        .WithMany()
                        .HasForeignKey("LegalRepresentativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyState");

                    b.Navigation("LegalRepresentative");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TravelAreaEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripAssignmentEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.AssignmentRoleEntity", "AssignmentRole")
                        .WithMany()
                        .HasForeignKey("AssignmentRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignmentRole");

                    b.Navigation("Person");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.LeadEntity", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TripStatesHistoryEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.TypeDocumentEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.DocumentCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Transporte.src.modules.transport.Infrastructure.entity.VehicleEntity", b =>
                {
                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.PersonEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.TypeVehicleEntity", "TypeVehicle")
                        .WithMany()
                        .HasForeignKey("TypeVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Transporte.src.modules.transport.Infrastructure.entity.VehicleStateEntity", "VehicleState")
                        .WithMany()
                        .HasForeignKey("VehicleStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("TypeVehicle");

                    b.Navigation("VehicleState");
                });
#pragma warning restore 612, 618
        }
    }
}
